# NOTE: Rules are sorted in ASCII order.

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3

plugins:
  - rubocop-rake
  - rubocop-rspec

Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true
  AllowSteepAnnotation: true

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 30

RSpec/NamedSubject:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
