AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3

plugins:
  - rubocop-rake
  - rubocop-rspec

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
