# NOTE: Rules are sorted in ASCII order.

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3

plugins:
  - rubocop-rake
  - rubocop-rspec

Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true
  AllowSteepAnnotation: true

Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  Exclude:
    - "lib/rubocop/herb/converter.rb"

Metrics/MethodLength:
  Max: 30

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
